<?xml version="1.0"?>
<robot name="mybot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Ajuste esses valores -->
  <xacro:property name="wheel_radius" value="0.0325"/>
  <xacro:property name="wheel_separation" value="0.155"/>

  <link name="base_link"/>
  <link name="left_wheel_link"/>
  <link name="right_wheel_link"/>
  <link name="imu_link"/>

  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <joint name="left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel_link"/>
    <origin xyz="0 ${wheel_separation/2} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <joint name="right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel_link"/>
    <origin xyz="0 -${wheel_separation/2} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- ros2_control: aponta para teu plugin -->
  <ros2_control name="MyBotSystem" type="system">
    <hardware>
      <plugin>bluepill_ros2_control/BluepillSystem</plugin>

      <!-- Ajuste -->
      <param name="serial_port">/dev/serial0</param>
      <param name="baud">115200</param>
      <param name="ticks_per_rev">2112</param>
      <param name="max_wheel_angular_velocity">20.0</param>
      <param name="encoders_are_incremental">false</param>
    </hardware>

    <joint name="left_wheel_joint">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>

    <joint name="right_wheel_joint">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
  </ros2_control>

</robot>
